config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  resources :cars do
    resources :bookings, only: %i[new create]
    resources :reviews, only: %i[new create]
  end
  resources :bookings, only: %i[edit update destroy]
  get 'profile', to: 'users#profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  enum status: { pending: 0, active: 1, archived: 2, destroying: 99 }

  belongs_to :car
  belongs_to :renter, class_name: "User"

  validates :start_date, :end_date, presence: true

  def duration
    (end_date - start_date).to_i
  end
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner, class_name: "User"

  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :brand, :model, :license_plate, :daily_price, :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many_attached :photos
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars_as_owner, class_name: "Car", foreign_key: :owner_id, dependent: :destroy
  has_many :bookings_as_renter, class_name: "Booking", foreign_key: :renter_id, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[destroy edit update]
  before_action :set_car, only: %i[new create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.renter = current_user

    @start_date = @booking.start_date
    @end_date = @booking.end_date

    unless @start_date.nil? || @end_date.nil?
      @number_of_days = (@end_date - @start_date).to_i
      @total_cost = @number_of_days * @car.daily_price / 100
      @booking.total_cost = @total_cost
    end

    if @booking.save
      redirect_to profile_path, notice: 'Booking successfully created.'
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  def destroy
    if @booking.status == 'destroying' || @booking.status == 'pending'
      @booking.destroy
      redirect_to profile_path, status: :see_other
    else
      @booking.status = 'destroying'
      @booking.save
    end
  end

  def edit
  end

  def update
    @car = @booking.car
    if params[:booking].key?(:start_date)
      @start_date = Date.parse(params[:booking][:start_date]).to_date
    else
      @start_date = @booking.start_date
    end

    if params[:booking].key?(:end_date)
      @end_date = Date.parse(params[:booking][:end_date]).to_date
    else
      @end_date = @booking.end_date
    end

    @number_of_days = (@end_date - @start_date).to_i
    @total_cost = @number_of_days * @car.daily_price / 100
    @booking.total_cost = @total_cost

    if @booking.valid?
      if @booking.status == 'pending' || @booking.status == 'destroying'
        @booking.update(booking_params)
        redirect_to profile_path, notice: 'Booking successfully updated.'
      else
        redirect_back fallback_location: edit_booking_path(@booking), notice: "This booking has already been accepted by the owner, and can't be updated."
      end

    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show destroy edit update]

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.daily_price = @car.daily_price * 100
    @user = current_user
    @car.owner = @user

    if @car.save
      redirect_to cars_path
    else
      render :new, status: :see_other
    end
  end

  def index
    respond_to do |format|
      format.html {
        @cars = Car.where(availability: true).order("id")
        @markers = @cars.geocoded.map do |car|
          {
            lat: car.latitude,
            lng: car.longitude,
            info_window_html: render_to_string(partial: "info_window", locals: { car: }),
            car_mark_html: render_to_string(partial: "car_mark", locals: { car: })
          }
        end
      }

      format.json {
        @map_json = map_params
        @near_cars = Car.near([@map_json['lat'], @map_json['lng']], 2).where(availability: true).order("id")
      }
    end
  end

  def show
    @booking = Booking.new
  end

  def edit
  end

  def update
    updated_params = car_params
    updated_params[:daily_price] = updated_params[:daily_price].to_i * 100

    if @car.update(updated_params)
      @car.daily_price = @car.daily_price * 100
      redirect_to profile_path, notice: 'Car successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @car.destroy

    redirect_to profile_path, status: :see_other
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :year, :category, :mileage,
                                :color, :license_plate, :description, :daily_price, :availability, :address, photos: [])
  end

  def map_params
    params.permit(:lat, :lng)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_car, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.car = @car
    if @review.save
      redirect_to @car, notice: 'Review was successfully created.'
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_car
    @car = Car.find(params[:car_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def rental_status(status)

    if status == 'archived'
      return 'btn btn-danger'
    elsif status == 'active'
      return 'btn btn-success'
    else
      return 'btn btn-warning'
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return "No rating" if rating.nil? # You can customize this message as needed
    "&#9733;" * rating
  end
end

app/views/bookings/edit.html.erb
<div class="edit-booking-container">
  <h1>Edit Booking</h1>

  <%= simple_form_for(@booking) do |f| %>
    <div class="form-group">
      <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
    </div>

    <div class="form-group">
      <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
    </div>

    <div class="form-group">
      <%= f.input :car_id, as: :hidden %>
    </div>

    <div class="form-group">
      <%= f.button :submit, "Update Booking", class: 'btn btn-primary' %>
    </div>
  <% end %>

  <%= link_to 'Back', profile_path, class: 'btn btn-secondary' %>
</div>

app/views/cars/_car_card.html.erb
<% @cars.each do |car| %>
  <div class="col-md-4 mb-4">
    <div class="card car-card">
      <%= cl_image_tag (car.photos[0].key), height: 200, width: 300, crop: :fill, class: "card-img-top" %>
      <div class="card-body d-flex flex-column">
        <h5 class="card-title"><%= car.year %> <%= car.brand %> <%= car.model %></h5>
        <p class="card-text flex-grow-1"><%= truncate(car.description, length: 100) %></p>
        <div class="d-flex justify-content-between align-items-center mb-3">
          <span class="btn btn-success card-price"><%= number_to_currency car.daily_price/100, precision: 0 %> per day</span>
          <%= link_to "Book Now!", car_path(car), class: "btn btn-primary" %>
        </div>
        <p class="card-owner mt-auto"><strong>Owner:</strong> <%= car.owner.first_name %> <%= car.owner.last_name %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/cars/_car_mark.html.erb
<%#= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>
<div class="badge border border-dark bg-white rounded-pill fs-6">
  <p class="text-dark m-0"><%= number_to_currency car.daily_price/100, precision: 0 %> </p>
</div>

app/views/cars/_info_window.html.erb
<div class="card h-100">
  <div class="card-body">
    <h5 class="card-title"><%= "#{car.year} #{car.brand} #{car.model}" %></h5>
    <p class="card-text"><strong>Mileage:</strong> <%= car.mileage %> km</p>
    <p class="card-text"><%= car.description %></p>
    <%= link_to 'Book Now', car_path(car), class: 'btn btn-primary mt-2' %>
  </div>
  <div class="card-footer text-muted">
    <small>Owner: <%= car.owner.first_name %> <%= car.owner.last_name %></small>
  </div>
</div>

app/views/cars/edit.html.erb
<div class="container">
  <h1>Edit my car</h1>

  <%= simple_form_for(@car) do |f| %>
    <%= f.input :brand, disabled: true %>
    <%= f.input :model, disabled: true %>
    <%= f.input :year, disabled: true %>
    <%= f.input :category, disabled: true %>
    <%= f.input :mileage %>
    <%= f.input :color %>
    <%= f.input :license_plate, disabled: true %>
    <%= f.input :description %>
    <%= f.input :daily_price, input_html: { value: @car.daily_price/100 }, hint: 'Price in dollars' %>
    <%= f.input :address,
    input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
    <%= f.input :availability, label: 'Available for listing?', hint: 'Uncheck this if you want to temporarily delist your car!', label_html: { class: "fw-bold" }%>
    <%= f.button :submit, class: "btn btn-primary mt-3"  %>
  <% end %>
</div>

<%# label_html: { value: 'my_class' } %>

app/views/cars/index.html.erb
<div class="container mt-3" data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  <div class="row mt-4">
    <div class="col-12 my-3" data-map-target="mainSearch"></div>
    <div class="col-lg-7 col-md-12 mb-4">
      <div class="row" data-map-target="carList">
        <%= render partial: 'cars/car_card', locals: { cars: @cars } %>
      </div>
    </div>
    <div class="col-lg-5 col-md-12">
      <div class="sticky-container">
        <div id="map" class="sticky-map" style="width: 100%; height: 600px;" data-map-target="pageMap"></div>
        <%= link_to 'List your car for rent!', new_car_path, class: 'btn btn-primary mt-3 w-100' %>
      </div>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container my-5">
  <%= simple_form_for @car do |f| %>
    <%= f.input :brand %>
    <%= f.input :model %>
    <%= f.input :year, hint: 'If you do not input the year, your car may not appear on certain filtered searches' %>
    <%= f.input :category %>
    <%= f.input :mileage %>
    <%= f.input :color %>
    <%= f.input :license_plate %>
    <%= f.input :description %>
    <%= f.input :daily_price, hint: 'Price in dollars' %>
    <%= f.input :address,
    input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit, class: "btn btn-primary mt-3" %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-6">
      <div id="carouselExampleIndicators" class="carousel slide carousel-fade">
        <div class="carousel-indicators">
          <% @car.photos.each_with_index do |photo, index| %>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>" aria-current="<%= 'true' if index == 0 %>" aria-label="Slide <%= index + 1 %>"></button>
          <% end %>
        </div>
        <div class="carousel-inner mb-3">
          <% @car.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>">
              <%= cl_image_tag (photo.key), height: 310, width: 600, crop: :fill, class: "d-block w-100" %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <h1><%= @car.year %> <%= @car.brand %> <%= @car.model%></h1>
      <p><strong>Type:</strong> <%= @car.category %></p>
      <p><strong>Color:</strong> <%= @car.color %></p>
      <p><strong>Mileage:</strong> <%= @car.mileage %> km</p>
      <p><strong>Owner:</strong> <%= @car.owner.first_name %> <%= @car.owner.last_name %></p>
      <p><strong>Description:</strong> <%= @car.description %></p>
      <p><strong>Address:</strong> <%= @car.address %></p>
    </div>
    <div class="col-md-6">
      <div class="card p-4">
        <h3 class="mb-3">Make a Booking</h3>
        <%= simple_form_for [@car, @booking] do |f| %>
          <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
          <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
          <%= link_to "Make Booking", new_car_booking_path(@car), class: "btn btn-primary w-100 mt-3" %>
        <% end %>
        <span class="btn btn-success text-white mt-3"><strong><%= number_to_currency @car.daily_price/100, precision: 0 %> per day</strong></span>
      </div>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-12">
      <div class="d-flex justify-content-between align-items-center">
        <h3>Reviews</h3>
        <%= link_to 'Leave a Review', new_car_review_path(@car), class: 'btn btn-secondary ms-3 rounded-3 text-white' %>
      </div>
      <% @car.reviews.each do |review| %>
        <div class="card mb-3">
          <div class="card-body">
            <p><strong><%= review.user.first_name %> <%= review.user.last_name %></strong></p>
            <p><%= raw star_rating(review.rating) %></p>
            <p><%= review.content %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsEzCar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://ga.jspm.io/npm:star-rating.js@4.3.0/dist/star-rating.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="main-content">
      <%= yield %>
    </div>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <img src="<%= asset_path 'ezcar_logotype.png' %>" alt="EzCar Logo" class="logo">
  <div class="search-container">
    <input type="text" class="search-bar" placeholder="Search for a car...">
    <%= link_to "Search for a car!", cars_path, class: "search-link btn btn-primary" %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="review-container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1>Leave a Review</h1>
      <%= simple_form_for([@car, @review], html: { data: { controller: 'form-submit' } }) do |f| %>
        <div class="form-group">
          <%= f.input :content, as: :text, input_html: { rows: 5 }, label_html: { class: 'form-label' }, wrapper: false, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: { data: { controller: "star-rating" } }, wrapper: false, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Send your review", class: "btn btn-primary mt-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class: "logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Rent cars", cars_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle text-white" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", profile_path, class: "dropdown-item" %>
              <%= link_to "List a new car", new_car_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/profile.html.erb
<div class="profile-container mt-3">
  <h1 class="mb-5">My Profile</h1>

  <%# Rentals Section %>
  <div class="rentals-section">
    <h3 class="my-3">Rentals</h3>
    <% active_bookings = @user.bookings_as_renter.order("id").select { |booking| booking.status != 'archived' } %>
    <% active_bookings.each do |booking| %>
      <div class="card mb-3 p-2">
        <% car = booking.car %>
        <% brand_model = "#{car.brand} #{car.model}" %>
        <%= link_to brand_model, car, class: 'btn btn-secondary mb-2' %>
        <p>From <%= booking.start_date.strftime("%d/%b/%Y") %> to <%= booking.end_date.strftime("%d/%b/%Y") %> (<%= booking.duration %> days)</p>
        <p>Total cost: <%= number_to_currency booking.total_cost, precision: 0 %></p>
        <div class="d-flex">
          <span class='<%= rental_status(booking.status)%> rounded-3 mx-3 text-white'><%= booking.status.capitalize %></span>
          <% edit_label = booking.status == 'active' || booking.status == 'destroying' ? 'Unable to edit active booking' : 'Edit this booking' %>
          <% edit_class = booking.status == 'active' || booking.status == 'destroying' ? 'disabled' : '' %>
          <%= link_to edit_label, edit_booking_path(booking), class: "btn btn-primary rounded-3 text-white #{edit_class}" %>
          <% destroy_label = booking.status == 'destroying' ? 'Delete request sent to car owner' : 'Delete this booking' %>
          <% destroy_class = booking.status == 'destroying' ? 'disabled' : '' %>
          <%= link_to destroy_label, booking_path(booking), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger ms-3 rounded-3 text-white #{destroy_class}" %>
          <%= link_to 'Leave a Review', new_car_review_path(car), class: 'btn btn-secondary ms-3 rounded-3 text-white' %>
        </div>
      </div>
    <% end %>
  </div>

  <%# My Cars Section %>
  <div class="my-cars-section">
    <h3 class="my-3"> My Cars</h3>
    <% @user.cars_as_owner.order("id").each do |car| %>
      <div class="card mb-3 p-2">
        <% brand_model = "#{car.brand} #{car.model}" %>
        <%= link_to brand_model, car, class: 'btn btn-secondary mb-2' %>
        <p>Daily Price: <%= number_to_currency car.daily_price.to_f/100, precision: 0 %></p>
        <p>Address: <%= car.address %></p>
        <% car_active_bookings = car.bookings.select { |booking| booking.status == 'active' } %>
        <p>Active Bookings : <%= car_active_bookings.count %></p>
        <div class="d-flex">
          <%= link_to 'Edit this car', edit_car_path(car), class: 'btn btn-primary' %>
          <%= link_to 'Delete this car', car_path(car), class: 'btn btn-danger ms-3 rounded-3 text-white', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
        </div>

        <%# Individual Car 'Bookings for...' div %>
        <div class="card mt-3 p-2">
          <% brand_model = "#{car.brand} #{car.model}" %>
          <h5><strong>Bookings for <%= brand_model %></strong></h5>

          <div class="card mt-3">
            <h6 class="m-3"><strong>Active Bookings</strong></h6>
            <% active_bookings = car.bookings.order("id").select { |booking| booking.status == 'active' || booking.status == 'destroying' } %>
            <% active_bookings.each do |booking| %>
              <div class="card m-3">
                <p>Renter: <%= booking.renter.first_name %> <%= booking.renter.last_name %></p>
                <p>Total income: <%= number_to_currency booking.total_cost, precision: 0 %></p>
                <p>From <%= booking.start_date.strftime("%d/%b/%Y") %> to <%= booking.end_date.strftime("%d/%b/%Y") %> (<%= booking.duration %> days)</p>
                <% destroy_class = booking.status == 'destroying' ? '' : 'd-none' %>
                <div class="mt-4 m-2 fw-bold <%= destroy_class %>">
                  <p class="m-0">Renter requested the deletion of this booking.</p>
                  <p class="m-0">What would you like to do?</p>
                  <div class="d-flex align-items-end">
                    <div>
                      <%= link_to 'Delete Booking', booking_path(booking), class: 'btn btn-danger fw-bold me-3', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
                    </div>
                    <%= simple_form_for booking do |f| %>
                      <%= f.input :status, as: :hidden, input_html: { value: 'active'} %>
                      <%= f.submit 'Keep booking', class: 'btn btn-success fw-bold' %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <h6 class="m-3"><strong>Pending Bookings</strong></h6>
          <div class="card">
            <% pending_bookings = car.bookings.order("id").select { |booking| booking.status == 'pending' } %>
            <% pending_bookings.each do |booking| %>
              <div class="card m-3">
                <p>Renter <%= booking.renter.first_name %> <%= booking.renter.last_name %></p>
                <p>Total income: <%= number_to_currency booking.total_cost, precision: 0 %></p>
                <p>From <%= booking.start_date.strftime("%d/%b/%Y") %> to <%= booking.end_date.strftime("%d/%b/%Y") %> (<%= booking.duration %> days)</p>
                <div class="d-flex">
                  <%= simple_form_for booking do |f| %>
                    <%= f.input :status, as: :hidden, input_html: { value: 'active'} %>
                    <%= f.submit 'Accept', class: 'btn btn-info' %>
                  <% end %>
                  <%= simple_form_for booking do |f| %>
                    <%= f.input :status, as: :hidden, input_html: { value: 'archived'} %>
                    <%= f.submit 'Reject', class: 'btn btn-light' %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>